---

- name: install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - bash

- name: add git user
  user:
    name: git
    shell: "/bin/ksh"
    comment: "{{ git_comment | default('Git User') }}"
